### ISSUE TITLE
Power Questions

### ISSUE THREAD

**Issue by joebowz** [olm3ca/mirror#4]
Hey guys, great work on all this. I'm about ready to start this project with my Mirror. I already bought the Vizio board, and I'm ordering the Rasberry-pi today.
One bit of information I find missing is how you setup the power? I'm assuming you're using the power supply that's already in the Mirror. The video shows a power plug inserted into the Vizio board but I don't know how you connected the other end to the power supply. I could play around with it but messing with high voltage make me nervous.

In addition to that I'm curious how the chrome book was also connected to power, or in my case it will be the Rasberry Pi.

Thanks for any help you can provide, and again thanks for documenting this project!

-Joe

**Comment by olm3ca** [comment]
Good question on power. We just connected power by merging the new devices (mainboard + chromebook motherboard) into the wires that lead into the plug next to the ethernet spot, i.e. where you attach the Mirror's plug on the unit. This has some advantages as it looks cleaner, but I'm actually thinking now that it might not have been ideal for my setup. 

Reason is, the Vizio mainboard needs to be turned on manually every time I turn on the Mirror (using the Vizio app or the [remote control](https://www.amazon.com/dp/B07L8BMYHJ?psc=1&ref=ppx_yo2ov_dt_b_product_details) I ordered). If I had just let the power cable from the Vizio come through the bottom of the device to be plugged in separately, it would remain on and only the Mirror's power would turn off. It would save the extra step of turning on two things but it would mean having the Vizio mainboard on all the time. Your call on what works best for you. 

The thing I'm enjoying about the chromebook is that we decided to keep the battery attached, so that system runs all day long and never needs to be turned on, but I can still access it via SSH at any time if I want to make changes to MagicMirror or the OS features I'm running. I wasn't sure at first but I'm glad we kept the battery there. Hope this helps!

**Comment by olm3ca** [comment]
All that is to say, if you're using the Pi - just route the power cables from the Vizio and the Pi through the hole where the ethernet cable used to be, and plug them in to a power strip. That way you can control each device as you want to.

**Comment by joebowz** [comment]
Thanks for your response, that makes sense. I think running separate cables through the bottom is the simplest solution for me. Just to confirm, since my vizio board didn't come with a power cable, it looks like that board takes AC in? So if I find a power cable to plug into it (as seen in your video) it should work? No power adapter needed?

**Comment by olm3ca** [comment]
Yeah I had an extra power cable I used, it's a very standard one most electronics use. Just bring the power cable up from the ethernet port to the Vizio board and you're all set.

**Comment by jmbherbert** [comment]
Hi all - loving this guide.  Managed to get my Vizio board installed yesterday, along with an old pi.  For power, I’d like the pi to have constant power (like u/olm3ca’s laptop) so i can ssh in, but the Vizio board and scalar board / backlight to be linked to the mirror power switch (so the screen isn’t drawing power the whole time). 

I was actually wondering whether there’s a way to route the power switch for the screen and Vizio board into the GPIO pins on the pi, so it could turn the screen and Vizio board on and off; for example on a timer or based on motion detection (I actually swapped out the mirror camera for the one I have with my pi).

I was thinking about replacing the C14 socket on the bottom of the mirror with this to accomplish that - I also kept the Ethernet to route into my pi if needed:  https://a.co/d/eAHjkRq

do you think that would work?

**Comment by olm3ca** [comment]
@jmbherbert - sounds like a very interesting idea. I just used a smart switch to power on / off the Mirror on a schedule, but others are interested in having motion sensors and other ways to wake the display. Please report back if you make progress on this!

**Comment by joebowz** [comment]
Hey guys, I finally got my mirror setup this weekend with a raspberry pi! Everything is working great, I have the mirror on my wall displaying time, temperature, and air quality.

One issue I'm having now is the screen will turn off after a couple of minutes. The IR light will still turn on and respond to the remote, but the screen itself doesn't appear to be backlit anymore. I also disabled screen saver for the pi (I think) so I'm mostly sure it's not the pi shutting down.

@jmbherbert I was reading your post and I wanted to clarify; it sounds like you're saying the Mirror power supply might be going into a power save mode? Correct me if I'm wrong, I might be reading too much into your post. If that were true it would explain my issue. My Vizio board and Pi are on separate power, the screen itself which is still using the Mirrors built in power supply appears to be shutting down. (it would make sense it's powering off the screen the same way it would when it was just an exercise mirror not being used)

I'm wondering if anyone else is running into this, and if this is indeed the case how can I keep it from going to sleep.

I'm also very interested in any progress for motion detection. That would be a cool feature.
@olm3ca I was actually considering a smart power switch too, but I need to solve this issue first.

**Comment by jmbherbert** [comment]
@joebowz you're ahead of me - I got everything to power up, but only with the back off and a bunch of additional cables.  I just ordered some shorter wires so that I can do a neater install inside the case.  I've had it running for a max of about 10 mins, so consequently I haven't hit the power save mode thing yet - though I could totally believe that's what's happening, as presumably the scalar board has no idea that it's not the thing controlling the display.

I also currently have the three things powered independently - the Vizio board, the Pi and the rest of the mirror (powerboard + scalar board + screen).  My current goal is to get all three powered through the one single C14 input at the base of the mirror, and so to do that I'm planning on using a splitter (something like this: https://a.co/d/fM4aPXk) and then trying to splice the Vizio power into the powerboard.  That'll leave me with the Pi always on, and the Vizio and remaining mirror pieces with button switches.  I was then going to try to use a relay (maybe this one - haven't decided yet: https://a.co/d/8sEWyrj) to replace those switches, so the Pi can control them.

Then from there, for motion detection I think there are a couple of options:
1) Just do presence detection and then:  https://projects.raspberrypi.org/en/projects/physical-computing/11
2) Do more sophisticated gesture recognition to enable interacting with the magic mirror (either with a sensor - like this person: https://okupatic.wordpress.com/2020/03/29/how-to-build-a-magic-mirror-and-not-die-trying/, or doing computer vision on the pi, like this: https://core-electronics.com.au/guides/hand-identification-raspberry-pi/)

**Comment by joebowz** [comment]
@jmbherbert That sounds great. I look forward to see the final result when you get all that setup. Once I get the power issue squared away, I would love to try the presence detection to turn the screen itself on. Maybe I can have the Vizio and Pi on all the time, but the screen only displays when you enter the room.

@olm3ca I missed that step! Is it possible to reset the Mirror through the app? Is it just a factory reset?

**Comment by olm3ca** [comment]
If you still have an active Mirror subscription, you should be able to use the app to reset it. Otherwise, it should just default to initial setup mode and in my case, the backlight just stays on now.

**Comment by jmbherbert** [comment]
re. factory reset - if you still have the scalar board in there and wired up, apparently holding down the little blue button at the top will do it for you:  https://www.reddit.com/r/lululemon/comments/tvjh8f/mirror_anyone_know_how_to_factory_reset_this_thing/

**Comment by joebowz** [comment]
That did it! I pressed the blue button for the reset. My smart mirror is now running without interruption!
Thanks for the help! Now I'm eyeing this idea of controlling the power with the pi :)

**Comment by olm3ca** [comment]
Great tip, @jmbherbert. I added this to Step 1 of the instructions.

**Comment by jmbherbert** [comment]
I managed to get everything working using the Pi and the relay, but I probably wouldn't recommend it.  Essentially I swapped out the push buttons for both the mirror and the Vizio into a relay, and am controlling that from the raspberry pi.

However, I'd probably actually use a smart plug for it if you have those.  The main reason is that the response time for the backlight and Vizio are different, and it's fiddly to work out what order to power them up in (the backlight takes quite a long time to fire up via the scalar board).

Ultimately I suspect I'm going to stick it on a timer, so a smart plug would likely have been fine, and would have left me with the physical buttons.

This setup would theoretically allow me to do motion detection, but you could do that with a smart plug anyway.  The main advantage is that I'm planning to run it off the single power input port at the base of the mirror.

![image](https://github.com/olm3ca/mirror/assets/37319198/c9861797-3077-4869-9bf6-f3fd29aeffe2)

**Comment by joebowz** [comment]
I have everything (Original Mirror power supply for scalar board, the vizio board, and the raspberry pi) individually plugged into a power strip so they all turn on at the same time, but I still have to use the remote to turn on the Vizio board. I wonder if this setup would be more beneficial if it only controlled the power to the scalar board / backlit screen? Everything else would always be on but the image wouldn't appear until motion is detected.

Though I guess you could technically do that with a smart switch for the scalar board, as you said.
Thanks for sharing your progress! It's giving me more ideas.

**Comment by olm3ca** [comment]
@joebowz this is why I left the Vizio powered on all the time. I got tired of turning on the Vizio each time. Since my laptop's battery is in the Mirror, it just slowly drains the battery in between on times (morning & night). But the Vizio is on all the time.

**Comment by jmbherbert** [comment]
So I'm leaning with @olm3ca on leaving the Vizio on all the time.

I tested running through the smart plug, and the Vizio + Pi is drawing about 20W.  The backlight adds another 40W.

My pi + relay can reliably turn the backlight + scalar board on and off, but it takes a while to come back up after being off - about 20s - so motion activation might be a bit much.  I might do something like put it on a switch off timer that resets every time it detects motion.

**Comment by joebowz** [comment]
So I bought this: [](https://www.amazon.com/dp/B009KSECO8?psc=1&ref=ppx_yo2ov_dt_b_product_details) and plugged the scalar board power into it. Now the screen will turn on when there's motion, and stay on for 10 minutes. (Vizio and Pi are always on) Similar issue, it takes 10-20 seconds for the scalar board to turn on. It's not too bad for me. 

Now if I were to nit pick, it would be really great if we can control the screens backlight. It's a bit too bright and at night very noticeable. I see an option to turn it down in the vizio menu, but the vizio board doesn't control the screen so.

I have a feeling this would be more of a challenge to figure out, and controlling the screen with the vizio would be the real solution.

**Comment by olm3ca** [comment]
@joebowz very cool motion sensor solution. I might just have to get that! And agreed on brightness... It actually helps to wake me up in the morning, but I wouldn't want it triggered at random times through the night by the cat ;-). 

We need to dig a little further on the re-pinning of the scalar board panel connector and how they could connect to the Vizio board. I'll need some time to do a bit more digging into this.

**Comment by Rabbitroyale** [comment]
> That did it! I pressed the blue button for the reset. My smart mirror is now running without interruption! Thanks for the help! Now I'm eyeing this idea of controlling the power with the pi :)

Hi! I'm having the same issue... I already changed the power board to the vizio, did you have to reconnect the old power board to get the reset button to work?

**Comment by joebowz** [comment]
> > That did it! I pressed the blue button for the reset. My smart mirror is now running without interruption! Thanks for the help! Now I'm eyeing this idea of controlling the power with the pi :)
> 
> Hi! I'm having the same issue... I already changed the power board to the vizio, did you have to reconnect the old power board to get the reset button to work?

I don't think so, I believe I did it when the Vizio board was already plugged in. It's been a few months and now my memory is fading.
