### ISSUE TITLE
For older model LTI400HN01

### ISSUE THREAD

**Issue by ryan-prichard** [olm3ca/mirror#9]
Has anyone found a control board for an older model that I purchased in 2020? I tried the link in the "other models" page but there's nothing there.

**Comment by olm3ca** [comment]
We looked into that panel at the outset of this project, and we didn't find a controller that would work with it out of the box. One suggestion was to repin LVDS to make it work with a programmable controller, but that idea hasn't moved forward.

**Comment by rooibos-hommes** [comment]
I just opened my mirror and noticed that I have the LTI400HN01 version. Any videos or tips on how to repin LVDS to  make them work with a programmable controller?

**Comment by mweth** [comment]
> I just opened my mirror and noticed that I have the LTI400HN01 version. Any videos or tips on how to repin LVDS to make them work with a programmable controller?

https://github.com/olm3ca/mirror/issues/8

**Comment by rooibos-hommes** [comment]
Hello all, I tried an off the shelf controller ([link](https://www.alibaba.com/product-detail/M53-V2-0-board-kit_1600759994284.html)). I connected it similarly to [avitascmore in Issue #8](https://github.com/olm3ca/mirror/issues/8), meaning that I only replaced the LVDS cable and let the rest of the screen remain powered by design. However I am getting the following pixelated image. Has anyone encountered a similar issue? What do you think is happening? 
![pixelatedMirror](https://github.com/olm3ca/mirror/assets/164579755/dbe4d4f0-86d3-4171-b990-6b7210fabeb1).
